spring:
      application:
                  name: ecommerce
      data:
        mongodb:
          uri: 
          ssl:
            enabled: true
          database : model
          auto-index-creation: true
      main:
        allow-circular-references: true
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
      mail:
        host: smtp.gmail.com
        port: 587
        username: 
        password: grxu avcq gswx ljsy
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true

#CLOUDINARY
cloudinary:
  cloud-name: dr1dlav3e
  api-key: 157134184454482
  api-secret: 6-Qd_IhZXNjHOuy8lGJZC-ggkgM

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        max-age: 360000
        path: /
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb: DEBUG



#      web:
#        cors:
#          allowed-origin-patterns: http://127.0.0.1:5500/
#          allowed-methods: GET,POST,PUT,DELETE
#          allowed-headers: ["*"]
#          allow-credentials: true
